// A stand-in AI provider for the e2e suite.
//
// **Editing this file is not enough — kill the running process too.** Playwright's
// `reuseExistingServer` means an already-listening stub on port 3100 is reused as-is, so
// a change here has no effect until the old one is stopped. This has now cost time twice,
// and the symptom is misleading: the tests fail as though the APP is broken.
//
//   Windows:  Get-NetTCPConnection -LocalPort 3100 -State Listen | Stop-Process -Id { $_.OwningProcess } -Force
//
// The companion cannot be tested against a real model: the output is non-deterministic by
// design, so there is no assertion to write about it. What CAN be tested is everything
// around the model — that a plan renders on the spine, that pruning changes the count,
// that an edit survives to the database, that Apply creates the right rows, that a
// refinement replaces the proposal rather than stacking a second one.
//
// So this speaks just enough of the OpenAI chat-completions protocol to stand in, and the
// app cannot tell the difference: it is reached through AI_BASE_URL like any other
// provider, and its answer goes through the same Zod parse. Real-model QUALITY stays
// permanently unverified in CI, which ADR-0011 accepts explicitly.

import { createServer } from "node:http"

const PORT = Number(process.env.AI_STUB_PORT ?? 3100)

/** `days` from today, as a YYYY-MM-DD wall date. */
function inDays(days) {
  const date = new Date()
  date.setUTCDate(date.getUTCDate() + days)
  return date.toISOString().slice(0, 10)
}

/**
 * Two shapes, so a refinement is distinguishable from a first generation.
 *
 * A refinement returns ONE milestone. That difference is the assertion: it proves the
 * instruction reached the provider and that the reply replaced the pending proposal
 * rather than creating a second one beside it.
 */
function planFor(isRefinement) {
  if (isRefinement) {
    return {
      milestones: [{ title: "STUB refined milestone", dueDate: inDays(30) }],
      habits: [{ title: "STUB refined habit", period: "week", targetCount: 2 }],
      setupTasks: [],
    }
  }
  // The T12c shape: a ladder, the practice that climbs it, and one genuine one-off. The
  // proportions are the point — most of the work is a rate, not a dated list.
  return {
    milestones: [
      { title: "STUB first milestone", dueDate: inDays(30) },
      { title: "STUB second milestone", dueDate: inDays(60) },
    ],
    habits: [{ title: "STUB practice", period: "week", targetCount: 3 }],
    setupTasks: [{ title: "STUB setup task", dueDate: inDays(7) }],
  }
}

/**
 * A routine. Offsets deliberately cover all three meanings — negative, zero, and null —
 * because collapsing them is the mistake the renderer has to not make.
 */
function routineFor(isRefinement) {
  if (isRefinement) {
    return {
      name: "STUB refined routine",
      description: "Revised",
      items: [
        { title: "STUB refined step", dueOffsetDays: 0, priority: "medium" },
      ],
    }
  }
  return {
    name: "STUB morning routine",
    description: "Generated by the stub provider",
    items: [
      {
        title: "STUB prep the night before",
        dueOffsetDays: -1,
        priority: "low",
      },
      { title: "STUB make coffee", dueOffsetDays: 0, priority: "medium" },
      { title: "STUB read something", dueOffsetDays: null, priority: "low" },
    ],
  }
}

/** A narrated week. Read-only, so there is nothing to prune — just prose to render. */
function summaryFor(isRefinement) {
  if (isRefinement) {
    return {
      headline: "STUB refined headline",
      observations: ["STUB refined observation."],
    }
  }
  return {
    headline: "STUB a steady week",
    observations: [
      "STUB you finished more on Wednesday than any other day.",
      "STUB meals were logged on five of seven days.",
    ],
  }
}

/**
 * Extracted transactions.
 *
 * One row names "Food" — an expense category, so it also satisfies `checkCategory`'s type
 * match — one names a category nothing will match, and one is income. That exercises the
 * renderer's matched / unmatched / income branches and gives the footer's uncategorised
 * count something to say.
 *
 * "Food" existing was ASSUMED here until it did not, on an account with no categories at
 * all: all three rows then landed uncategorised and the spec's counts were each off by one.
 * `companion.spec.ts` now seeds it (`ensureFoodCategory`) rather than hoping. If this name
 * changes, change it there too — the two are a pair.
 *
 * Dated TODAY, not a fixed date: `/budget` opens on the current month, so a row dated in
 * some other month is created correctly and then invisible — which reads in a test as
 * "Apply did nothing".
 */
function importFor(isRefinement) {
  if (isRefinement) {
    return {
      rows: [
        {
          date: inDays(0),
          payee: "STUB refined payee",
          description: "",
          amount: 1,
          type: "expense",
          categoryName: null,
        },
      ],
    }
  }
  return {
    rows: [
      {
        date: inDays(0),
        payee: "STUB TESCO",
        description: "weekly shop",
        amount: 42.1,
        type: "expense",
        categoryName: "Food",
      },
      {
        date: inDays(0),
        payee: "STUB UNKNOWNCO",
        description: "",
        amount: 9.99,
        type: "expense",
        categoryName: "No Such Category",
      },
      {
        date: inDays(0),
        payee: "STUB SALARY",
        description: "",
        amount: 2400,
        type: "income",
        categoryName: null,
      },
    ],
  }
}

/**
 * What this stub claims to serve, for the Settings model dropdown (T12h).
 *
 * `stub` first because `ai.setup.ts` configures the suite to use it; the second exists so
 * a spec can switch models and prove the choice persists, which needs two of something.
 * Shaped like an OpenAI-compatible `/models` response — `{ data: [{ id }] }` — which is
 * also the shape Anthropic uses, so one body covers both protocols.
 */
const MODELS = { object: "list", data: [{ id: "stub" }, { id: "stub-alt" }] }

const server = createServer((request, response) => {
  // Answered because the app now ASKS: a provider that 404s here leaves the settings page
  // with an empty dropdown and no way to choose. A stub that cannot be configured through
  // the UI it is standing in for is not standing in for much.
  if (request.url?.endsWith("/models")) {
    response.writeHead(200, { "Content-Type": "application/json" })
    response.end(JSON.stringify(MODELS))
    return
  }

  if (!request.url?.endsWith("/chat/completions")) {
    response.writeHead(404).end()
    return
  }

  let body = ""
  request.on("data", (chunk) => {
    body += chunk
  })
  request.on("end", () => {
    // Keyed off what was actually sent rather than off a call counter, so the stub stays
    // honest: if the app stops sending the brief or the revision phrase, these break.
    const isRoutine = body.includes("Design a routine for")
    const isSummary = body.includes("Tasks completed:")
    const isImport = body.includes("Text to read:")
    const isRefinement =
      body.includes("Revise this existing plan") ||
      body.includes("Revise this existing routine") ||
      body.includes("Revise this existing summary") ||
      body.includes("Revise this existing extraction")
    const payload = isImport
      ? importFor(isRefinement)
      : isSummary
        ? summaryFor(isRefinement)
        : isRoutine
          ? routineFor(isRefinement)
          : planFor(isRefinement)

    response.writeHead(200, { "Content-Type": "application/json" })
    response.end(
      JSON.stringify({
        choices: [
          { message: { role: "assistant", content: JSON.stringify(payload) } },
        ],
      }),
    )
  })
})

server.listen(PORT, "127.0.0.1", () => {
  // Playwright waits for this port to accept connections before starting the suite.
  console.log(`ai-stub listening on http://127.0.0.1:${PORT}`)
})
